### ISSUE TITLE
Had to delete pipfile.lock

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-sqlalchemy-one-to-many#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/208545?module_item_id=480724

### Concern

I had to delete the pipfile.lock and reinstall for this reading too in order to use alembic commands. Otherwise I received this no module error:

```
ModuleNotFoundError: No module named 'importlib_resources'
```

Not sure if other people have experienced this error or if it's just me.

**Comment by DakotaLMartinez** [comment]
I've got the same issue on my machine. It looks like the same issue as this lab: https://github.com/learn-co-curriculum/python-p3-working-with-seed-data/issues/2. The `pytest` dependency is what adds `importlib-resources` and `importlib-metadata` and prevents that error. Would be nice if they were dependencies of `albemic` instead...

**Comment by Matt-Eva** [comment]
Gotcha, thanks Dakota!

**Comment by professor-ben** [comment]
I added in the hard-coded import. I'm not sure why pytest (and later, flask) aren't collecting this when they're installed, but we're just going to take the manual approach to it from now on.
