### ISSUE TITLE
Prepopulated Database

### ISSUE THREAD

**Issue by joemilius** [learn-co-curriculum/python-p3-sqlalchemy-one-to-many#6]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

After cloning this lab and walking through the instructions I encountered an error when running alembic upgrade head to create the database: Failed: Can't locate revision identified by '2c73f79151bd'.  After some investigation I saw that the database was already populated with data, so I theorized that a migration was missing from the clone that set the database to its current state and could not be reverted back with out that migration.  I did find that the solution code did still pass the tests but I assume we want students to see how the process works in a successful manor. The error and database are included in this screen shot: 
![image](https://user-images.githubusercontent.com/82882813/215178385-5362fe5f-75f9-4036-b0bd-2179c11c4b9a.png)

### Suggested Changes

The way I fixed this is by looking in the solution branch for the migration (which was there) then creating a copy of that migration in my own directory.  I then downgraded the database to the migration given in the clone with: alembic downgrade 0d06041c7860.  Then I deleted the migration file I copied from the solution branch.  After that all the instructions in the canvas lesson worked perfectly (well except for the second test that is looking for a review_score attribute instead of a score attribute, but Dakota already patched that one, it just needs to be changed on the main branch.  I would recommend downgrading the database on the main branch so that it is empty when students clone it.

**Comment by professor-ben** [comment]
The database should *definitely* not be there. I'll take care of this now. Thanks for raising the issue!
